### PR TITLE
Fix domain examples and manual dns hook

### PR DESCRIPTION
**Pull request by jbjonesjr**
- Added 2 additional subdomains to the subdomain example
- Updated the normal domains example to have equivalent example domains
- Add a hook to do manual domain validation

### CODE REVIEW

**Comment by jbjonesjr** [comment]
Have updated the domain text, and completed my manual hook code.

This lives independently as well at https://github.com/jbjonesjr/letsencrypt-manual-hook

I'm done with my changes. :ship:

**Comment by cjs** [comment]
@jbjonesjr I'd like to leave the `domains.txt.example` file alone, since it comes from upstream.

**Comment by jbjonesjr** [comment]
Makes sense, totally agree. Could we replace GitHub.example with just example in the other file then? I'm a big fan of consistency for things like his.

**Comment by cjs** [comment]
I was wrong, merging as is.

**Pull request merged**
